---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

```{r}
exhibit1 <- exhibit1 %>%
  mutate(rate = resp / nr_mailed,
         type = paste0(apr,'_',fixed_var,'_',annual_fee))
```


Average
```{r}
sum(exhibit1$resp) / sum(exhibit1$nr_mailed)


```








```{r}

## Gather columns
pfg <- gather(exhibit1, resp, freq, non_resp, resp, factor_key = TRUE)
## register the new dataset
register("pfg", "exhibit1")
```


```{r}
pfg_150 <- pfg %>%
  filter(bk_score == 150) %>%
  select(date:freq)
register("pfg_150", "pfg")


pfg_200 <- pfg %>%
  filter(bk_score == 200) %>%
  select(date:freq)
register("pfg_200", "pfg")
## filter and sort the dataset
pfg_250 <- pfg %>%
  filter(bk_score == 250) %>%
  select(date:freq)
register("pfg_250", "pfg")
# dtab(pfg_250, dec = 2, nr = 100) %>% render()
```

```{r fig.width = 7, fig.height = 5.38, dpi = 144}
result <- logistic(
  pfg_150, 
  rvar = "resp", 
  evar = c("apr", "fixed_var", "annual_fee"), 
  lev = "resp", 
  wts = "freq"
)
summary(result)
#plot(result, plots = "dist", custom = FALSE)
```
```{r}
result <- logistic(
  pfg_200, 
  rvar = "resp", 
  evar = c("apr", "annual_fee"), 
  lev = "resp", 
  wts = "freq"
)
summary(result)
```


pfg_200 has no example of variable


```{r}
result <- logistic(
  pfg_250, 
  rvar = "resp", 
  evar = c("apr", "fixed_var", "annual_fee"), 
  lev = "resp", 
  wts = "freq"
)
summary(result)
```



```{r}
result <- doe(
  factors = c(
    "apr; 14.9; 16.8; 19.8", 
    "annual_fee; 0; 20", 
    "fixed_var; 'fixed'; 'var'", 
    "bk; 150; 200; 250"
  ), 
  trials = 12, 
  seed = 1234
)
summary(result, eff = TRUE, part = TRUE, full = TRUE)
```



```{r}

a <- exhibit1%>%
  group_by(type) %>%
  summarize(what = sum(resp) / sum(nr_mailed)) %>%
  filter(type %in% c('14.9_Variable_0','14.9_Fixed_20','16.8_Variable_0','16.8_Fixed_20','19.8_Fixed_0','19.8_Variable_20'))

```



```{r}

b <- exhibit1 %>%
  group_by(type) %>%
  summarize(what = sum(resp) / sum(nr_mailed)) %>%
  arrange(desc(what))

```



```{r}

pfg_250_dat <- select(pfg_250, date, apr, fixed_var, annual_fee, visamc, nr_mailed, bk_score, average_bk, resp, freq) %>%
  table2data("freq")
```



```{r}
pfg_250_ <- sample_n(pfg_250_dat, 18000)
result <- logistic(
  pfg_250_, 
  rvar = "resp", 
  evar = c("apr", "fixed_var", "annual_fee"), 
  lev = "resp", 
  #wts = "freq"
)
summary(result)



```

```{r}
pfg_150 <- read_csv("pfg_150.csv")
pfg_200 <- read_csv("pfg_200.csv")
pfg_250 <- read_csv("pfg_250.csv")

```

```{r}
exhibit2 <- mutate_at(exhibit2, .vars = vars(apr, annual_fee), .funs = as_factor)

```

```{r}
pfg_150 <- mutate(pfg_150, no_resp = Sent - Responses)
pfg_200 <- mutate(pfg_200, no_resp = Sent - Responses)
pfg_250 <- mutate(pfg_250, no_resp = Sent - Responses)
```



```{r}
pfg_150 <- gather(pfg_150, responce, freq, Responses, no_resp, factor_key = TRUE)
pfg_200 <- gather(pfg_200, responce, freq, Responses, no_resp, factor_key = TRUE)
pfg_250 <- gather(pfg_250, responce, freq, Responses, no_resp, factor_key = TRUE)
```


```{r}
pfg_150 <- mutate_at(pfg_150, .vars = vars(apr, annual_fee), .funs = as_factor)
pfg_200 <- mutate_at(pfg_200, .vars = vars(apr, annual_fee), .funs = as_factor)
pfg_250 <- mutate_at(pfg_250, .vars = vars(apr, annual_fee), .funs = as_factor)
```

pfg_150
```{r}
result <- logistic(
  pfg_150, 
  rvar = "responce", 
  evar = c("apr", "fixed_var", "annual_fee"), 
  lev = "Responses", 
  wts = "freq"
)
summary(result)


pred <- predict(result, pred_data = exhibit2)
print(pred, n = 10)
exhibit2 <- store(exhibit2, pred, name = "pred_150")
exhibit2$pred_150_lower <- pred$`2.5%`
exhibit2$pred_150_higher <- pred$`97.5%`
```


pfg_200

```{r}

result <- logistic(
  pfg_200, 
  rvar = "responce", 
  evar = c("apr", "fixed_var", "annual_fee"), 
  lev = "Responses", 
  wts = "freq"
)
summary(result)

pred <- predict(result, pred_data = exhibit2)
print(pred, n = 10)
exhibit2 <- store(exhibit2, pred, name = "pred_200")
exhibit2$pred_200_lower <- pred$`2.5%`
exhibit2$pred_200_higher <- pred$`97.5%`
```

pfg_250


```{r}

result <- logistic(
  pfg_250, 
  rvar = "responce", 
  evar = c("apr", "fixed_var", "annual_fee"), 
  lev = "Responses", 
  wts = "freq"
)
summary(result)

pred <- predict(result, pred_data = exhibit2)
print(pred, n = 10)
exhibit2 <- store(exhibit2, pred, name = "pred_250")
exhibit2$pred_250_lower <- pred$`2.5%`
exhibit2$pred_250_higher <- pred$`97.5%`
```



```{r}
exhibit2 <- exhibit2 %>%
  mutate(profit_150 = ltv150*pred_150,
         profit_200 = ltv200*pred_200,
         profit_250 = ltv250*pred_250)
```


```{r}
exhibit2 <- exhibit2 %>%
  mutate(profit_150_lower = ltv150*pred_150_lower,
         profit_150_higher = ltv150*pred_150_higher,
         profit_200_lower = ltv200*pred_200_lower,
         profit_200_higher = ltv200*pred_200_higher,
         profit_250_lower = ltv250*pred_250_lower,
         profit_250_higher = ltv250*pred_250_higher,)


```


```{r}
send_150 <- exhibit2 %>%
  arrange(desc(profit_150) )%>%
            slice(1)


send_200 <- exhibit2 %>%
  arrange(desc(profit_200) )%>%
            slice(1)



send_250 <- exhibit2 %>%
  arrange(desc(profit_250) )%>%
            slice(1)

```


favorite product by cutomer

```{r}
exhibit2[which.max(exhibit2$pred_150),]
exhibit2[which.max(exhibit2$pred_200),]
exhibit2[which.max(exhibit2$pred_250),]

```




```{r}
exhibit2[which.max(exhibit2$profit_150_lower),]
exhibit2[which.max(exhibit2$profit_200_lower),]
exhibit2[which.max(exhibit2$profit_250_lower),]

```



```{r}
exhibit2[which.max(exhibit2$profit_150_higher),]
exhibit2[which.max(exhibit2$profit_200_higher),]
exhibit2[which.max(exhibit2$profit_250_higher),]

```


```{r}
result <- nn(
  pfg_150, 
  rvar = "responce", 
  evar = c("apr", "fixed_var", "annual_fee"), 
  lev = "Responses", 
  wts = "freq", 
  seed = 1234
)
summary(result, prn = TRUE)
pred <- predict(result, pred_data = exhibit2)
print(pred, n = 10)
exhibit2 <- store(exhibit2, pred, name = "pred_nn_150")
```



```{r}
result <- nn(
  pfg_200, 
  rvar = "responce", 
  evar = c("apr", "fixed_var", "annual_fee"), 
  lev = "Responses", 
  wts = "freq", 
  seed = 1234
)
summary(result, prn = TRUE)
pred <- predict(result, pred_data = exhibit2)
print(pred, n = 10)
exhibit2 <- store(exhibit2, pred, name = "pred_nn_200")
```





```{r}
result <- nn(
  pfg_250, 
  rvar = "responce", 
  evar = c("apr", "fixed_var", "annual_fee"), 
  lev = "Responses", 
  wts = "freq", 
  seed = 1234
)
summary(result, prn = TRUE)
pred <- predict(result, pred_data = exhibit2)
print(pred, n = 10)
exhibit2 <- store(exhibit2, pred, name = "pred_nn_250")
```


```{r}
exhibit2 <- exhibit2 %>%
  mutate(profit_nn_150 = ltv150*pred_nn_150,
         profit_nn_200 = ltv200*pred_nn_200,
         profit_nn_250 = ltv250*pred_nn_250)

```


```{r}
exhibit2[which.max(exhibit2$profit_nn_150),]
exhibit2[which.max(exhibit2$profit_nn_200),]
exhibit2[which.max(exhibit2$profit_nn_250),]

```



```{r}
exhibit2[which.max(exhibit2$pred_nn_150),]
exhibit2[which.max(exhibit2$pred_nn_200),]
exhibit2[which.max(exhibit2$pred_nn_250),]

```
Ensemble

```{r}
exhibit2 <- exhibit2 %>%
  mutate(ensemble_150  = (pred_150 +pred_nn_150) / 2,
         ensemble_200  = (pred_200 +pred_nn_200) / 2,
         ensemble_250  = (pred_250 +pred_nn_250) / 2,
         profit_ensem_150 = ensemble_150 * ltv150,
         profit_ensem_200 = ensemble_200 * ltv200,
         profit_ensem_250 = ensemble_250 * ltv250)

```



```{r}
exhibit2[which.max(exhibit2$profit_ensem_150),]
exhibit2[which.max(exhibit2$profit_ensem_200),]
exhibit2[which.max(exhibit2$profit_ensem_250),]

```
